% This script generates the diaschisis figure for Lobule VII
% This plots SC PC3 vs EPM Open Arm Pref for Lob VII mice and their
% matched controls as well as SVM fits
% 
% Originally in: ../2016-11-07 - sfn figs

%% Setup
% Let's start clean :)
clear, clc, close all

% Add dependencies to the path
addpath(genpath('deps'))

% Analysis data generated by ksAnalysis.m
ksAnalysisPath = 'data/2017-08-31-ks_analysis.mat';

% SVM figs path
svmFigPath = 'figs/svm';
if ~exists(svmFigPath); mkdir(svmFigPath); end

%% Load
load(ksAnalysisPath)

% Pull out data
X1 = sc.LobuleVII.Adult;  X2 = sc.LobuleVII.Juven;
Y1 = epm.LobuleVII.Adult; Y2 = epm.LobuleVII.Juven;

%% Make sure the data lines up
% Pull out unique mouse names
expt_mice1 = intersect(X1.mice(~X1.isCtrl), Y1.mice(~Y1.isCtrl));
expt_mice2 = intersect(X2.mice(~X2.isCtrl), Y2.mice(~Y2.isCtrl));

ctrl_mice1 = intersect(X1.mice(X1.isCtrl), Y1.mice(Y1.isCtrl));
ctrl_mice2 = intersect(X2.mice(X2.isCtrl), Y2.mice(Y2.isCtrl));

% Merge data points
expt_pts1 = [X1.all.SC_PC3(expt_mice1), Y1.all.EPM_OpenArmPref(expt_mice1)];
expt_pts2 = [X2.all.SC_PC3(expt_mice2), Y2.all.EPM_OpenArmPref(expt_mice2)];

ctrl_pts1 = [X1.all.SC_PC3(ctrl_mice1), Y1.all.EPM_OpenArmPref(ctrl_mice1)];
ctrl_pts2 = [X2.all.SC_PC3(ctrl_mice2), Y2.all.EPM_OpenArmPref(ctrl_mice2)];

%% SVM
[data1,G1] = cellcat({expt_pts1; ctrl_pts1},1);
svm1 = fit_hit_svm(data1,G1,2);

[data2,G2] = cellcat({expt_pts2; ctrl_pts2},1);
svm2 = fit_hit_svm(data2,G2,2);

%% Plot
fig = figure('Renderer','painters');
hold on

% Scatter
h = [];
h(1) = plotpts(expt_pts1,'x', 'Color', 'r');
h(2) = plotpts(ctrl_pts1,'o', 'Color', 0.5 .* [1 1 1]);
h(3) = plotpts(ctrl_pts2,'o', 'Color', 0.7 .* [1 1 1]);
h(4) = plotpts(expt_pts2,'x', 'Color', 'b');
set(h, 'MarkerSize',12, 'LineWidth',3)

% Scatter legend
grp_legend = {'Acute Lobule VII', 'Acute Control', 'Developmental Controls', 'Developmental Lobule VII'};
N = arrayfun(@(x)numel(get(x,'XData')),h);
grp_legend = cf(@(x,n)sprintf('%s (n = %s)',x,n), grp_legend,cellstr(string(N)));

% SVM
hsvm = [];
hsvm(1) = plotpts(svm1.Cpts,'r-');
hsvm(2) = plotpts(svm2.Cpts,'b-');
svm_legend = {'SVM (Adult vs Control)', 'SVM (Developmental vs Control)'};

% Legend
hleg = legend([h, hsvm] , [grp_legend, svm_legend],'Location','northwest');

% Misc formatting
graygrid
xlabel('SC PC3: Exploratory and Sociable Behavior','FontWeight','bold')
ylabel('EPM Open Arm Preference Index','FontWeight','bold')
fontsize(16)
figsize(875,700)

% Save
export_fig(ff(svmFigPath, 'lob7_diaschisis'), '-eps', '-png')